### ISSUE TITLE
ditto: cpio read error: bad file format

### ISSUE THREAD

**Issue by basdeg** [autopkg/grahamgilbert-recipes#43]
The recipe produces the following error: 

```
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
{'Output': {}}
FlatPkgUnpacker
{'Input': {'destination_path': '/Users/cadmin/Library/AutoPkg/Cache/local.munki.GoogleChromeEnterprise/unpack',
           'flat_pkg_path': '/Users/cadmin/Library/AutoPkg/Cache/local.munki.GoogleChromeEnterprise/downloads/GoogleChrome.pkg'}}
FlatPkgUnpacker: Unpacked /Users/cadmin/Library/AutoPkg/Cache/local.munki.GoogleChromeEnterprise/downloads/GoogleChrome.pkg to /Users/cadmin/Library/AutoPkg/Cache/local.munki.GoogleChromeEnterprise/unpack
{'Output': {}}
PkgPayloadUnpacker
{'Input': {'destination_path': '/Users/cadmin/Library/AutoPkg/Cache/local.munki.GoogleChromeEnterprise/payload/Applications',
           'pkg_payload_path': '/Users/cadmin/Library/AutoPkg/Cache/local.munki.GoogleChromeEnterprise/unpack/GoogleChrome.pkg/Payload'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/PkgPayloadUnpacker.py", line 97, in main
    self.unpack_pkg_payload()
  File "/Library/AutoPkg/autopkglib/PkgPayloadUnpacker.py", line 88, in unpack_pkg_payload
    raise ProcessorError(
autopkglib.ProcessorError: extraction of /Users/cadmin/Library/AutoPkg/Cache/local.munki.GoogleChromeEnterprise/unpack/GoogleChrome.pkg/Payload with ditto failed: ditto: cpio read error: bad file format

  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
extraction of /Users/cadmin/Library/AutoPkg/Cache/local.munki.GoogleChromeEnterprise/unpack/GoogleChrome.pkg/Payload with ditto failed: ditto: cpio read error: bad file format

Failed.
Receipt written to /Users/cadmin/Library/AutoPkg/Cache/local.munki.GoogleChromeEnterprise/receipts/GoogleChromeEnterprise.munki-receipt-20221208-091432.plist

The following recipes failed:
    GoogleChromeEnterprise.munki.recipe
        Error in local.munki.GoogleChromeEnterprise: Processor: PkgPayloadUnpacker: Error: extraction of /Users/cadmin/Library/AutoPkg/Cache/local.munki.GoogleChromeEnterprise/unpack/GoogleChrome.pkg/Payload with ditto failed: ditto: cpio read error: bad file format

Nothing downloaded, packaged or imported.
```

In another recipe i use for Google Drive, i had to replace the payloadUnpacker with PBXZPayloadUnpacker custom processor. https://github.com/autopkg/hjuutilainen-recipes/blob/master/TeamViewer/PBXZPayloadUnpacker.py

**Comment by basdeg** [comment]
I now see that the recipe is moved. sorry for this.
